[package]
name = "minimodal"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.18", features = ["cargo"]}
crossterm = "0.28.1"
ratatui = { version = "0.28.1", features = ["unstable-rendered-line-info"] }
